In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [2]:
data = pd.read_csv('../heart.csv')

In [3]:
# Convert non-numeric data to numeric data
le = LabelEncoder()
data['sex'] = le.fit_transform(data['sex'])
data['cp'] = le.fit_transform(data['cp'])
data['fbs'] = le.fit_transform(data['fbs'])
data['restecg'] = le.fit_transform(data['restecg'])
data['exang'] = le.fit_transform(data['exang'])
data['slope'] = le.fit_transform(data['slope'])
data['thal'] = le.fit_transform(data['thal'])
data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [4]:
X=data.drop(['target'], axis =1)
y=data['target']

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [26]:
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression(max_iter=1000)
logreg.fit(X_train, y_train)
predictions1 = logreg.predict(X_test)

In [27]:
from sklearn.metrics import confusion_matrix, classification_report

print("Confusion Matrix: \n", confusion_matrix(y_test, predictions1))
print('\n')
print(classification_report(y_test, predictions1))

Confusion Matrix:
 [[73 29]
 [13 90]]


              precision    recall  f1-score   support

           0       0.85      0.72      0.78       102
           1       0.76      0.87      0.81       103

    accuracy                           0.80       205
   macro avg       0.80      0.79      0.79       205
weighted avg       0.80      0.80      0.79       205

In [6]:
data.sample(frac=1)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
510,54,0,1,132,288,1,0,159,1,0.0,2,1,2,1
803,52,1,0,112,230,0,1,160,0,0.0,2,1,2,0
690,58,1,2,105,240,0,0,154,1,0.6,1,0,3,1
228,52,1,1,128,205,1,1,184,0,0.0,2,0,2,1
907,50,0,1,120,244,0,1,162,0,1.1,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
986,55,0,0,180,327,0,2,117,1,3.4,1,0,2,0
868,56,1,1,120,240,0,1,169,0,0.0,0,0,2,1
485,62,1,1,120,281,0,0,103,0,1.4,1,1,3,0
462,52,1,3,118,186,0,0,190,0,0.0,1,0,1,1
306,44,0,2,118,242,0,1,149,0,0.3,1,1,2,1

In [7]:
cl1 = data[:256]
cl2 = data[256:]

In [8]:
cl1.to_csv('./cl1.csv', encoding='utf-8')
cl2.to_csv('./cl2.csv', encoding='utf-8')