In [8]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [5]:
data = pd.read_csv('../heart.csv')

In [6]:
# Convert non-numeric data to numeric data
le = LabelEncoder()
data['sex'] = le.fit_transform(data['sex'])
data['cp'] = le.fit_transform(data['cp'])
data['fbs'] = le.fit_transform(data['fbs'])
data['restecg'] = le.fit_transform(data['restecg'])
data['exang'] = le.fit_transform(data['exang'])
data['slope'] = le.fit_transform(data['slope'])
data['thal'] = le.fit_transform(data['thal'])
data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [7]:
X=data.drop(['target'], axis =1)
y=data['target']

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [26]:
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression(max_iter=1000)
logreg.fit(X_train, y_train)
predictions1 = logreg.predict(X_test)

In [27]:
from sklearn.metrics import confusion_matrix, classification_report

print("Confusion Matrix: \n", confusion_matrix(y_test, predictions1))
print('\n')
print(classification_report(y_test, predictions1))

Confusion Matrix:
 [[73 29]
 [13 90]]


              precision    recall  f1-score   support

           0       0.85      0.72      0.78       102
           1       0.76      0.87      0.81       103

    accuracy                           0.80       205
   macro avg       0.80      0.79      0.79       205
weighted avg       0.80      0.80      0.79       205

In [31]:
data.sample(frac=1)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
393,62,0,0,160,164,0,0,145,0,6.2,0,3,3,0
412,57,1,0,150,276,0,0,112,1,0.6,1,1,1,0
535,76,0,2,140,197,0,2,116,0,1.1,1,0,2,1
551,54,1,0,122,286,0,0,116,1,3.2,1,2,2,0
468,61,1,2,150,243,1,1,137,1,1.0,1,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
802,63,0,0,124,197,0,1,136,1,0.0,1,0,2,0
265,45,1,0,104,208,0,0,148,1,3.0,1,0,2,1
578,62,0,0,140,394,0,0,157,0,1.2,1,0,2,1
610,43,0,0,132,341,1,0,136,1,3.0,1,0,3,0

In [32]:
cl1 = data[:500]
cl2 = data[500:]

In [ ]:
cl1.to_csv('./cl1.csv', encoding='utf-8')
cl2.to_csv('./cl2.csv', encoding='utf-8')